name: run-actions-using-diff-files
run-name: ãƒ—ãƒ«ãƒªã‚¯ãƒ¡ãƒƒã‚»ãƒ¼ã‚¸ç”Ÿæˆ Action ğŸš€
on:
  pull_request:
    types: [opened,reopened]

env:
  base_branch: main
  diff_path: '**.py'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  run-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Switch to pull request branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Fetch base branch
        run: git fetch origin ${base_branch}:${base_branch}

      - name: Run actions using diff_files
        id: git-diff
        run: |
          diffs=$(git diff ${base_branch} HEAD  -- "${diff_path}" \
            | tr "\n" " ")
          echo "# diffs: ${diffs}"
          echo "DIFFS=${diffs}" >> $GITHUB_OUTPUT
      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 1.29.58
          arch: amd64    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: generate pr description
        env: 
          S3_DOWNLOAD_BUCKET: ${{ secrets.S3_DOWNLOAD_BUCKET }}
          DIFFS: ${{ steps.git-diff.outputs.DIFFS }}
        run: |
          aws bedrock-runtime invoke-model \
          --model-id anthropic.claude-v2 \
          --body "{\"prompt\": \"\n\nHuman:ä»¥ä¸‹ã®ã€ã€‘å†…ã®gitã®diffã‚’è¦‹ã¦ã€ã€${DIFFS}ã€‘ ãƒ—ãƒ«ãƒªã‚¯ã‚¨ã‚¹ãƒˆã®descriptionã‚’ãã®ã¾ã¾è²¼ã‚Œã‚‹æ–‡è¨€ã§ä½œæˆã—ã¦ã€‚ã‚µãƒ³ãƒ—ãƒ«ã¨ãªã‚‹å‡ºåŠ›ã¯[]å†…ã®ãƒ†ã‚­ã‚¹ãƒˆã‚’å‚ç…§ã—ã¦ã­ã€‚[## ã‚„ã£ãŸã“ã¨\n\n* ã“ã®ãƒ—ãƒ«ãƒªã‚¯ã§ä½•ã‚’ã—ãŸã®ã‹ï¼Ÿ\n\n## ã‚„ã‚‰ãªã„ã“ã¨\n\n* ã“ã®ãƒ—ãƒ«ãƒªã‚¯ã§ã‚„ã‚‰ãªã„ã“ã¨ã¯ä½•ã‹ï¼Ÿï¼ˆã‚ã‚Œã°ã€‚ç„¡ã„ãªã‚‰ã€Œç„¡ã—ã€ã§OKï¼‰ï¼ˆã‚„ã‚‰ãªã„å ´åˆã¯ã€ã„ã¤ã‚„ã‚‹ã®ã‹ã‚’æ˜è¨˜ã™ã‚‹ã€‚ï¼‰\n\n## ã§ãã‚‹ã‚ˆã†ã«ãªã‚‹ã“ã¨ï¼ˆãƒ¦ãƒ¼ã‚¶ç›®ç·šï¼‰\n\n* ä½•ãŒã§ãã‚‹ã‚ˆã†ã«ãªã‚‹ã®ã‹ï¼Ÿï¼ˆã‚ã‚Œã°ã€‚ç„¡ã„ãªã‚‰ã€Œç„¡ã—ã€ã§OKï¼‰\n\n## ã§ããªããªã‚‹ã“ã¨ï¼ˆãƒ¦ãƒ¼ã‚¶ç›®ç·šï¼‰\n\n* ä½•ãŒã§ããªããªã‚‹ã®ã‹ï¼Ÿï¼ˆã‚ã‚Œã°ã€‚ç„¡ã„ãªã‚‰ã€Œç„¡ã—ã€ã§OKï¼‰\n\n## å‹•ä½œç¢ºèª\n\n* ãƒ¬ãƒ“ãƒ¥ãƒ¯ãƒ¼ã¸ã®å‚è€ƒæƒ…å ±] \n\nAssistant:\", \"max_tokens_to_sample\":1000}" invoke-model-output.txt
      - name: cat invoke-model-output.txt
        id: invoke-model-output
        env: 
          S3_DOWNLOAD_BUCKET: ${{ secrets.S3_DOWNLOAD_BUCKET }}
        run: |
          cat invoke-model-output.txt
          description=$(cat invoke-model-output.txt | jq -r .completion)
          
          echo  'DESCRIPTION<<EOF'  >> "$GITHUB_OUTPUT"
          echo "${description}"  >> "$GITHUB_OUTPUT"
          echo 'EOF' >> "$GITHUB_OUTPUT"

      - name: URL to Pull Request description
        env:
          DESCRIPTION: ${{ steps.invoke-model-output.outputs.DESCRIPTION }}
        run: |
          DESCRIPTION_TEXT=$(echo $DESCRIPTION)
          gh pr edit ${{ github.event.pull_request.number }} --body "${DESCRIPTION_TEXT}"
           
